variables:
  PROJECT_PORT: 30001 ## 工程的端口

build:
  stage: build
  only:
    - master
  tags:
    - spring-cloud-k8s
  script:
    - mvn clean package -Dmaven.test.skip=true

    - DIST_JAR_PATH=`find . -iname "*.jar" -not -iname "*-sources.jar"`
    - DIST_JAR_NAME=`echo $DIST_JAR_PATH | rev | cut -d'/' -f 1 | rev`
    - IMAGE_NAME=registry.cn-shenzhen.aliyuncs.com/hudeshun/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_JOB_ID

    - mkdir -p outputs outputs/$CI_PROJECT_NAME
    - pwd
    - cp -rf $DIST_JAR_PATH outputs/
    - echo "构建Dockerfile"
    - cp Dockerfile outputs/Dockerfile
    - sed -i '' -e "s#DIST_JAR_PATH#$DIST_JAR_NAME#g" -e "s#DIST_JAR_NAME#$DIST_JAR_NAME#g" -e "s#PROJECT_PORT#$PROJECT_PORT#g" outputs/Dockerfile

    - echo "构建Deployment"
    - cp deploy.yml outputs/deploy.yml
    - sed -i '' -e "s#PROJECT_NAME#$CI_PROJECT_NAME#g" -e "s#REPLACE_IMAGE#$IMAGE_NAME#g" -e "s#PROJECT_PORT#$PROJECT_PORT#g" outputs/deploy.yml

    - docker login --username=$ALIYUN_USER_NAME registry.cn-shenzhen.aliyuncs.com -p $ALIYUN_USER_PASSWORD
    - docker build --tag $IMAGE_NAME outputs/
    - docker push $IMAGE_NAME
    - docker rmi $IMAGE_NAME

    - ssh -i ~/.ssh/id_rsa root@$K8S_MASTER_IP -C "pwd"

    - ssh -i ~/.ssh/id_rsa root@$K8S_MASTER_IP -C "mkdir -p /tmp/$CI_PROJECT_NAME"
    - scp -qr outputs/deploy.yml root@$K8S_MASTER_IP:/tmp/$CI_PROJECT_NAME
    - ssh -i ~/.ssh/id_rsa root@$K8S_MASTER_IP -C "kubectl apply -f /tmp/$CI_PROJECT_NAME/deploy.yml"
